### ISSUE TITLE
Scope of the questionnaire - only targeting terminology providers or also consumers?

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#1]
Feedback on questionnaire from @mabablue transferred from team discussion:
With this questionnaire, you collect terminologies only, but not annotation practices e.g. as done by data centres like PANGAEA. I thought we should include those too, but I am not sure how this could be done if we use these questions. Is it thought to collect those sort of practices later on? Also because I think not all terminologies might have a whole set of components needed for a complete description of observable properties but only cover parts of it.

**Comment by gwemon** [comment]
Is "annotation practice" not a use case of the terminologies?

**Comment by graybeal** [comment]
The term 'annotation practices' is a bit hard to grok (because I think of annotating text with controlled terms, sorry!). 

For many communities I think 'annotation practices' are performed through descriptive information, not the name. (Think of CF conventions, where the equivalent to our observable property is the standard name, then there is a name/label, then there is a description. People specialize the description with a lot of detail.

I can see asking for that detail, but it risks moving the task into the "how do I describe everything about this variable?" rather than "how do I name this variable?" The former includes an arbitrarily long tail of provenance and context; the latter is more like CF's "standard name". (Which, incidentally, is not required, and often is just not feasible because the variable is too different from the goals of the standard name.)  

Am I correct in thinking i-ADOPT is trying to create standard naming protocols for observable variables, not full definitions of them?

**Comment by mabablue** [comment]
@graybeal and @gwemon what I wanted to say here is something different: will data centres, which are not terminology developers themselves be able to answer to this questionnaire? They may annotate their data with different terminologies. 
About your @graybeal comment about the full definitions, I think we will be somewhere in between, we will have to decide. In my PhD I will go for the full definitions...

**Comment by pbuttigieg** [comment]
I think we need two questionnaires that can be sent out in the same email. One targeting developers and the other annotators and other primary users

We should be open : we are doing much more than just creating interoperable names. Extended notes as annotations are valuable to us too, and I agree these are the norm. We should get a sense of how these notes are formed and what their main content axes are so we can make the framework feel as natural as possible.

We will, of course, have to draw the line somewhere, and the surveys should help us figure out where that is.

**Comment by gwemon** [comment]
I fear that if we add annotation practices to the questionnaire about terminology management and development we risk confusing the users. @kitchenprinzessin3880 and @mabablue could you come up with suggestions of questions you'd like to see as part of the questionnaire on annotation practices?

**Comment by kitchenprinzessin3880** [comment]
> I think we need two questionnaires that can be sent out in the same email. One targeting developers and the other annotators and other primary users

I agree with @pbuttigieg. we need two separate questionnaires, one for provider and the other for consumer. the consumer questionnaire may reuse some questions from the provider-centric questionnaire though.

**Comment by mabablue** [comment]
@gwemon yes I can work on this together with @kitchenprinzessin3880 .. not sure if we will be ready before Monday though

**Comment by mabablue** [comment]
@gwemon I provided a new questionnaire for consumers (https://docs.google.com/forms/d/1X5xE492Tir5yPi0BrmF2aA4bOcozYafzE_0olrL7K64/edit) and changed on a separate copy the one for providers (https://docs.google.com/forms/d/1bUKcMviJr9UGUS6haVo_IcR0TRVxdNAISsPouE55Fpo/edit) to have a the end interoperable answers see issue #21 with tables for the examples and terminology entities used.

**Comment by gwemon** [comment]
I think this can now be closed. Decision is to go for 2 questionnaires.

**Comment by mabablue** [comment]
well not totally sure... still @graybeal argued that many respondent will have a double role and so they have to answer twice... we could also have a forked questionnaire... with a general part for both roles and then asking... are you a terminology provider or user or both... and then go to the specific questions
