### ISSUE TITLE
observable property vs variables

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#12]
@mabablue asked: should we always use the term observable property (like the title of the group) or variables?

**Comment by SirkoS** [comment]
At least within the survey the term used should stay the same. Otherwise, respondent might wonder, if there are two distinct concepts and how they differ from one another.

**Comment by graybeal** [comment]
In formal communication like this survey I'd use a formal, less conflicted term that can be defined up front. So 'observable property' is better from this perspective. 

In conversation where everyone is up to speed we can say 'variables', but we have to be thoughtful, because it will have other connotations for people. (As does 'observable properties', but it's less common and a bit more of a precise match for what we mean.)

**Comment by pbuttigieg** [comment]
Observable property is more neutral. As long as it's explained it should work.

"Variable" is something more active, an assigned role on an observable property in a study (all things, even constants, have some jitter)

**Comment by gwemon** [comment]
I believe this is now fixed. I have replaced "variables" by "observable properties" or "observations" as appropriate for all but 3 which I have left as "variables" because I feel that using "observable property" in those 3 cases would not be correct. Let me know if you disagree.
