### ISSUE TITLE
questionnaire options: view other submissions, edit response

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#14]
After filling in the questionnaire for the first time, it is now possible to
a) see all other contributions
b) edit your response
c) submit another response

Do we all agree with keeping these 3 options?

**Comment by graybeal** [comment]
I endorse all 3, I think it will improve the answers and give everyone the ability to see the landscape more clearly.

Because I'm pretty sure it's impossible to be anonymous, I suggest that you (a) make clear that the person's responses will be visible to other respondees, and (b) offer the option to send you (or anyone else) responses offline for anonymous entry under someone else's name. We could also offer an 'interview' option, where a volunteer (I'd be willing) walks the person through the form and fills out the person's answers, anonymizing the name. 

(But really, public visibility of the answers means someone would have a decent chance of figuring out who filled the form out, even if anonymous.)

**Comment by mabablue** [comment]
well if we agree that we let all other contributions be openly accessible we have to add this in the closing statement of the questionnaire
