### ISSUE TITLE
domain versus cross-domain versus cross-level

### ISSUE THREAD

**Issue by mabablue** [i-adopt/terminologies#38]
I think it is important that the question should not overlap. 
Therefore there should be a question related to the (1) domain, one related to (2) cross-domain aspects (physical, chemical, taxonomic (species), spatial) and one related (3) to cross-level aspects (complex, modelled, statistical, dimensional). I don't see the necessity to have biodiversity etc. in (2) as well.

**Comment by gwemon** [comment]
I agree to removing biodiversity from the cross-domain because it is already listed in B4 however you need to have a category in the cross-domain for non-species related biological variable names. Also if we have taxonomic data then we may want to also have a distinct tick box for genomic and biomolecular data. Also I would remove "spatial" as a category. For the 3rd level I would add some text to explain what you mean by some of these terms. Maybe some examples would help here.

**Comment by mabablue** [comment]
Why is biological a cross domain category? We could have biology as a domain...or am I wrong?

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by mabablue** [comment]
I think genomic or biomolecular are not so relevant for the environmental domain as taxonomic, there is always the possibility to add others

**Comment by mabablue** [comment]
it looks now like this: 
![image](https://user-images.githubusercontent.com/32859932/72781742-53296d80-3c22-11ea-861f-aec1c33c8dfd.png)
