### ISSUE TITLE
link to data repositories/products/systems

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#5]
@mabablue feedback issue transferred from team discussion:
About question: Please name the main data repository(ies), systems or data products that use your terminology

1- There could be more than one answer, so if you want to properly use them for later analysis, they should be addressed in specific boxes... or at least we should indicate to use a semi-column or something similar for post-editing to provide better analysis options later on, if helpful (I am always struggling with google forms when more than one answer can be given to a specific question).

2- On the other hand, there could also be no repository that the developer is aware of and thus I suggest to not make this question obligatory.

**Comment by gwemon** [comment]
I don't think it is possible to add individual boxes on demand when responding to a google form. I think that the best option might be to ask for respondent to separate multiple responses with semi-colons (same for: If possible please provide URLs or DOIs of example data set(s)). I suggest we do that rather than over-complicating the form.
Then regarding #2 above I can't imagine a case where a respondent to this kind of questionnaire would not know at least a few of the data system/product/repositories that use their terminologies. However I take your point that it could be a rare possibility and I am proposing to keep this question mandatory but maybe tell respondent to indicate "none", "unknown" or "many others" if this is the case.

**Comment by mabablue** [comment]
fine with both suggestions

**Comment by SirkoS** [comment]
(1) I suggest to replace the semicolon as a separator by "one entry per line". In my experience people wont adhere to that syntax anyway, but if they do, one per line is easy enough to parse and is (usually) in no conflict with any symbols used within names

(2) In my opinion, we want to gather information about the use of terminologies etc. in practice. The "in practice" to my implies that there is some system and/or product that actually makes use of the terminology. So for the (hopefully improbable) case that the terminology is not used, I think people would add something along "none" or similar even without mentioning that in the question itself. The mentioning of that might entice people to make use of that instead of actually thinking more about an answer.

**Comment by gwemon** [comment]
@SirkoS I agree with your (1) - I thought this was not possible in Google form but I have just tried it and it seems to work. Shall we say "one entry per line, ending each line with a semi colon"?
Note sure about (2) as I imagine that the people going through the effort of filling in the questionnaire will understand our purpose and will be keen to contribute info if they know it. So personally, I think I would prefer to give them unambiguous options covering all possible cases.

**Comment by graybeal** [comment]
(1) Just '(one entry per line)'. Details are your enemy in this complicated questionnaire.
(2) Provide explicit unambiguous options only if they add strongly to your planned analytics. I worry about required answers and detailed instructions. (see (1))

**Comment by gwemon** [comment]
One per line added to question:
Please name the main data repository(ies), systems or data products that use your terminology (one per line)
Left question as mandatory and open as suggested by Sirko.

**Comment by mabablue** [comment]
the issue is that it is not possible to have more than one line
