### ISSUE TITLE
Request to submit list of nitrogen variables as a file attachment

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#6]
Feedback from @mabablue  transferred from team discussion: Please provide a list of nitrogen-related variable names held in your terminology isn't this asked already two questions before?

**Comment by gwemon** [comment]
@mabablue No this is a different level of granularity. The checkboxes that were provided two questions before asked for broad data types related to nitrogen. Here we are asking for the list of actual variable names (e.g. not concentration of nitrogen in water bodies but concentration per unit volume of a water body of e.g. nitrate plus nitrite). This is extra, non compulsory information. It could be very helpful in giving us very specific examples to compare how various terminologies represent specific variables.

**Comment by SirkoS** [comment]
I'm unsure about the burden that this places upon a participant. Assuming a large terminology this basically asks people to go through all the terms and decide, whether they are applicable to nitrogen in some way. Also the format and/or storage of the vocabulary might not lend itself to compiling such a list (thinking of an RDF-vocabulary here) and thus require even more work.

Section 1 already asks for a URL to the resource. Isn't that already giving us the names in question? Admittedly without the filtering ...

**Comment by graybeal** [comment]
(a) Don't ask for all of them, just a few examples. As @SirkoS says we can get all the names if we need them.
(b) Example answers for every question, please, especially this one, which needs several different kinds of answers: one or two each from CF, Pangaea, BCO-DMO, Maria's voc, something you make up from SWEET, and make sure there's at least one simple one.

**Comment by mabablue** [comment]
I think this has to be done in a second step. When we actually try to bring that together in a matrix (excel sheet).

**Comment by gwemon** [comment]
I don't think that to specifically ask for examples would be very useful. So I have made a couple of changes that will address the concerns of restricting format and burden to the respondent: (1) I have removed the need to submit a specific file format and (2) I have changed the descriptive text to remove "spreadsheet" and "full list". It is now: 
"If you can, please upload a file containing a list of nitrogen-related observable properties described in your terminology."

**Comment by mariutzica** [comment]
@gwemon I am not seeing the changes to the [form](https://docs.google.com/forms/d/1bUKcMviJr9UGUS6haVo_IcR0TRVxdNAISsPouE55Fpo/edit); is this because I am looking at a copy that does not have the most recent updates? 

One thing that came to mind here was to combine this question with the other question -- users can either fill in the checklist provided or they can upload a file (or they can provide a link, see next paragraph), whichever they prefer. So maybe two of the options for the previous question could be "I am uploading a file with details" and "I am providing a link to a site that can be used to access this information." This way, if it is easier for someone to just upload a file or provide a link, they don't have to also fill out the checklist.

In terms of providing the nitrogen related variables, I would say performing a simple search on their variables for "nitrogen" and providing us the results (or top 50 results if there are hundreds of results) in whatever format is probably the simplest approach if they do not have time to curate. Even more easy, if they have a search tool online that we can use to do the search ourselves, they could just point us to that, like for example the [CF standard name browser](http://cfconventions.org/Data/cf-standard-names/69/build/cf-standard-name-table.html).

**Comment by mabablue** [comment]
@mariutzica Gwen changed the original questionnaire which is here: https://docs.google.com/forms/d/1G6T3sHuBih8H7JsW-67akshUvQmkSCAQt2Q99qcGARo/edit. I wanted to make sure that we don't change that one, as it is so hard to restore the original (no version management). The link in the readme section of the terminology repository shows only the copy of that questionnare which is not updated yet.

**Comment by mabablue** [comment]
@gwemon are you asking for 'complex property names' as I use it?

**Comment by gwemon** [comment]
@mabablue No. This question is about the name attached to the value field. For example a full P01 preflabel or a full CF standard name or whatever text you use to "name" your variable so for some it might be simply "Ammonium".

**Comment by gwemon** [comment]
ooops sorry I closed by mistake!
